version: '3.8'

services:
  app:
    build: .
    container_name: tuaobra-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tuaobra
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: dev12345
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - default

  db:
    image: postgres:13
    container_name: tuaobra-db
    environment:
      POSTGRES_DB: tuaobra
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev12345
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - default

  adminer:
    image: adminer
    container_name: tuaobra-adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - default

volumes:
  postgres-data:
    driver: local

networks:
  default:
    driver: bridge